version: '3.8'

services:
  web01:
    build: .
    container_name: millos-web01
    environment:
      - PORT=8080
      - NODE_ENV=production
      - API_KEY=secure-api-key-2024
    ports:
      - "8081:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  web02:
    build: .
    container_name: millos-web02
    environment:
      - PORT=8080
      - NODE_ENV=production
      - API_KEY=secure-api-key-2024
    ports:
      - "8082:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  loadbalancer:
    image: haproxy:2.8-alpine
    container_name: millos-lb
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web01
      - web02
    restart: unless-stopped